version: "2.2"
services:

  # MySQL Server
  mysql_database:
    container_name: mysql_database
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306' # external:internal
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node_server:
    container_name: node_server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: base
    depends_on:
      - mysql_database
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PASS_SECRET: ${PASS_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NODE_PORT: ${NODE_PORT}
    volumes:
      - type: bind
        source: ./server/src
        target: /home/node/app/src
      - ./server/nodemon.json:/home/node/app/nodemon.json
    expose:
      - '${NODE_PORT}'
    ports:
      - '${NODE_PORT}:${NODE_PORT}'
    command: yarn dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
